"""Replication of the Shen, Song & Abadie (2025) Monte-Carlo study (Section 6).

Shen, Z., Song, X. & Abadie, A. (2025), *Efficiently Learning Synthetic Control
Models for High-dimensional Disaggregated Data* (arXiv:2510.22828).

This reproduces the simulation design for the **MSC** estimator (the paper's
name for the Multivariate Square-root Lasso SC that mlsynth ships as ``MSQRT``):

Design
------
* ``T0`` pre-treatment periods, ``T1`` post-treatment periods, ``n`` controls,
  ``m`` treated units (swept over a grid), ``s`` total non-zeros in ``Theta``.
* Controls ``X`` follow an AR(1):  ``Y_{i,t} = 0.1*c_i + 0.9*Y_{i,t-1} + Z``,
  ``c_i in {1..10}``, ``Z ~ N(0, 1)``.
* **Setting (1)** -- treated units generated by the *same* AR(1) process
  (no true sparse SC representation; misspecified).
* **Setting (2)** -- treated units generated by ``Y = X Theta + E`` with a
  random ``s``-sparse ``Theta`` whose columns sum to 1 and ``E ~ N(0, sigma^2)``
  (well-specified sparse SC).

No treatment effect is injected, so the true ATT ``delta = 0`` and the reported
**ATT bias** ``delta_hat - delta`` is the mean counterfactual-prediction error
at the first post-period (paper eq. 1). The **RMSE** is the root-mean-square
error of the predicted ``Y(0)`` over all ``T1`` post-periods (paper Table 1).

The paper's headline parameters (``PAPER``) are ``n=400``, ``T0=100``,
``T1=10``, ``s=1000``, ``m in {50,100,150,200,250,300,350,400}``, 500 reps.
Those nuclear-norm programs are large; ``DEMO`` is a proportionally scaled
preset (same ``s/n``, ``m/n`` and ``s/m`` ratios) that runs quickly and
directionally reproduces the findings.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# Data-generating process
# ---------------------------------------------------------------------------

def ar1_panel(n: int, T: int, rng: np.random.Generator, *, burn: int = 50) -> np.ndarray:
    """AR(1) panel, time-major ``(T, n)``: ``Y_t = 0.1 c + 0.9 Y_{t-1} + Z``."""
    c = (np.arange(n) % 10 + 1).astype(float)          # c_i in {1, ..., 10}
    Y = np.zeros((n, T + burn))
    Y[:, 0] = c                                        # start at stationary mean
    for t in range(1, T + burn):
        Y[:, t] = 0.1 * c + 0.9 * Y[:, t - 1] + rng.normal(size=n)
    return Y[:, burn:].T                               # drop burn-in -> (T, n)


def random_theta(n: int, m: int, s: int, rng: np.random.Generator) -> np.ndarray:
    """Random ``(n, m)`` weight matrix with ``s`` total non-zeros, columns sum to 1."""
    Theta = np.zeros((n, m))
    # Spread s non-zeros across columns as evenly as possible (>= 1 each).
    base, extra = divmod(s, m)
    per_col = np.full(m, base, dtype=int)
    per_col[:extra] += 1
    per_col = np.clip(per_col, 1, n)
    for j in range(m):
        idx = rng.choice(n, size=int(per_col[j]), replace=False)
        w = rng.random(int(per_col[j]))
        Theta[idx, j] = w / w.sum()                    # column sums to 1
    return Theta


def simulate_shen2025(setting: int, m: int, *, n: int, T0: int, T1: int,
                      s: int, sigma: float, rng: np.random.Generator):
    """One Monte-Carlo draw. Returns ``(X, Y_treated)`` time-major over T0+T1."""
    T = T0 + T1
    X = ar1_panel(n, T, rng)                           # (T, n)
    if setting == 1:
        Y = ar1_panel(m, T, rng)                       # treated ~ same AR(1)
    elif setting == 2:
        Theta = random_theta(n, m, s, rng)
        E = rng.normal(scale=sigma, size=(T, m))
        Y = X @ Theta + E                              # well-specified sparse SC
    else:
        raise ValueError("setting must be 1 or 2")
    return X, Y


def to_long_df(X: np.ndarray, Y: np.ndarray, T0: int) -> pd.DataFrame:
    """Stack control matrix ``X (T,n)`` and treated matrix ``Y (T,m)`` into the
    long panel MSQRT expects: columns ``unit``, ``time``, ``Y``, ``treated``.

    Treated units (one block, common adoption) switch on at period ``T0``; no
    treatment effect is injected, so the observed outcome *is* ``Y(0)``.
    """
    T, n = X.shape
    m = Y.shape[1]
    # Zero-padded names so lexical sort matches numeric order (c000.., t000..).
    cw, tw = len(str(n - 1)), len(str(m - 1))
    ctrl_names = np.array([f"c{j:0{cw}d}" for j in range(n)])
    trt_names = np.array([f"t{j:0{tw}d}" for j in range(m)])
    names = np.concatenate([ctrl_names, trt_names])
    vals = np.hstack([X, Y]).T                          # ((n+m), T)
    units = np.repeat(names, T)
    times = np.tile(np.arange(T), n + m)
    treated = np.zeros((n + m, T), dtype=int)
    treated[n:, T0:] = 1                                # treated block, t >= T0
    return pd.DataFrame({
        "unit": units, "time": times,
        "Y": vals.reshape(-1), "treated": treated.reshape(-1),
    })


# ---------------------------------------------------------------------------
# Metrics for one draw -- via the public MSQRT.fit() API
# ---------------------------------------------------------------------------

def _one_run(X, Y, T0, lambd):
    """Fit the shipped ``MSQRT`` estimator and score the post-period.

    Metrics are read off the returned ``MSQRTResults``:

    * **ATT bias** = ``att_t[0]`` -- the mean treated gap at the first
      post-period (paper eq. 1; the true ATT is 0, so the gap *is* the bias).
    * **RMSE** = root-mean-square of ``gap`` over the post window -- the
      counterfactual-prediction error for ``Y(0)`` (paper Table 1).
    """
    from ...estimators.msqrt import MSQRT       # local import: avoids cycles

    df = to_long_df(X, Y, T0)
    res = MSQRT({
        "df": df, "outcome": "Y", "treat": "treated",
        "unitid": "unit", "time": "time",
        "lambda_": float(lambd),                # pre-selected once (paper)
        "inference": False, "display_graphs": False,
    }).fit()
    att_bias = float(res.att_t[0])
    post_gap = res.gap[res.inputs.T0:]          # (T1, m) observed - synthetic
    rmse = float(np.sqrt(np.mean(post_gap ** 2)))
    return att_bias, rmse


# ---------------------------------------------------------------------------
# Presets
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SimConfig:
    n: int
    T0: int
    T1: int
    s: int
    sigma: float
    m_grid: List[int]
    n_reps: int
    lambda_grid: List[float] = field(
        default_factory=lambda: list(np.logspace(-2, 1, 6)))


PAPER = SimConfig(n=400, T0=100, T1=10, s=1000, sigma=0.5,
                  m_grid=[50, 100, 150, 200, 250, 300, 350, 400], n_reps=500)

# A fast, directional regime: keeps the paper's pre-period length (T0=100, so
# recovery is near the noise floor) and its donor-sparsity ratios (s/n = 2.5;
# per-column non-zeros sweep 18.75 -> 2.5, matching the paper's m=50 -> m=400
# endpoints), but at n=150 so every solve finishes in ~1-3 s. Reproduces the
# qualitative findings (RMSE roughly flat in m; ATT bias centred at zero).
# Use ``PAPER`` (and real compute) for the exact n=400, 500-replication study.
DEMO = SimConfig(n=150, T0=100, T1=10, s=375, sigma=0.5,
                 m_grid=[20, 40, 60, 80, 100, 120, 150], n_reps=10)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def run_msqrt_simulation(cfg: SimConfig = DEMO, *, settings=(1, 2),
                         seed: int = 0, lambda_override: Optional[float] = None,
                         verbose: bool = True) -> Dict:
    """Run the MSC Monte-Carlo and return summary tables per setting.

    For each setting the L1 penalty is **pre-selected once** (as in the paper)
    by rolling-origin CV on a representative draw, then reused across all
    ``m`` and replications. Pass ``lambda_override`` to fix the penalty and
    skip CV (much faster -- CV is many extra solves).

    Returns
    -------
    dict
        ``{setting: list of {m, rmse_mean, rmse_std, bias_mean, bias_std}}``.
    """
    from ...estimators.msqrt import MSQRT

    rng = np.random.default_rng(seed)
    out: Dict[int, List[dict]] = {}
    for setting in settings:
        if lambda_override is not None:
            lambd = float(lambda_override)
        else:
            # Pre-select lambda once: a single MSQRT.fit() with CV on a draw.
            m_mid = cfg.m_grid[len(cfg.m_grid) // 2]
            Xc, Yc = simulate_shen2025(setting, m_mid, n=cfg.n, T0=cfg.T0,
                                       T1=cfg.T1, s=cfg.s, sigma=cfg.sigma, rng=rng)
            lambd = MSQRT({
                "df": to_long_df(Xc, Yc, cfg.T0), "outcome": "Y",
                "treat": "treated", "unitid": "unit", "time": "time",
                "n_lambda": len(cfg.lambda_grid),
                "inference": False, "display_graphs": False,
            }).fit().best_lambda
        if verbose:
            print(f"\n=== Setting ({setting}) | pre-selected lambda = {lambd:.4f} ===")
            print(f"{'m':>5} {'RMSE mean':>10} {'RMSE std':>9} "
                  f"{'bias mean':>10} {'bias std':>9}")
        rows = []
        for m in cfg.m_grid:
            biases, rmses = [], []
            for _ in range(cfg.n_reps):
                X, Y = simulate_shen2025(setting, m, n=cfg.n, T0=cfg.T0,
                                         T1=cfg.T1, s=cfg.s, sigma=cfg.sigma, rng=rng)
                b, r = _one_run(X, Y, cfg.T0, lambd)
                biases.append(b); rmses.append(r)
            row = {"m": m,
                   "rmse_mean": float(np.mean(rmses)),
                   "rmse_std": float(np.std(rmses)),
                   "bias_mean": float(np.mean(biases)),
                   "bias_std": float(np.std(biases))}
            rows.append(row)
            if verbose:
                print(f"{m:>5} {row['rmse_mean']:>10.3f} {row['rmse_std']:>9.3f} "
                      f"{row['bias_mean']:>+10.4f} {row['bias_std']:>9.4f}")
        out[setting] = rows
    return out


if __name__ == "__main__":
    run_msqrt_simulation(DEMO)
