"""Step-level agreement between the DMLFM port and pblasso 1.0.8.

Every conditional draw in ``src/blasso.cpp`` factors into a deterministic mean
and covariance plus a normal draw. The RNG streams cannot be matched across
languages, but the deterministic halves can, exactly. These tests pin them
against fixtures generated by calling the reference's own Rcpp functions, so a
divergence names the step that is wrong instead of leaving an end-to-end number
to guess at.

Regenerate the fixtures with the script recorded in
``benchmarks/reference/dmlfm_germany/README.md``; it needs pblasso 1.0.8 from
the authors' replication package.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pytest

from mlsynth.utils.dmlfm_helpers.sampler import _group_moments, _tilde, _tilde_tau
from mlsynth.utils.dmlfm_helpers.setup import _starts

FIX = pathlib.Path(__file__).parent / "fixtures" / "dmlfm" / "sampler_steps.json"
TOL = 1e-10


@pytest.fixture(scope="module")
def fx():
    if not FIX.exists():  # pragma: no cover - fixture is committed
        pytest.skip("pblasso fixtures not generated")
    return json.loads(FIX.read_text())


def arr(x):
    return np.asarray(x, float)


def test_group_starts_match_breakID(fx):
    id0 = arr(fx["inputs"]["id0"]).astype(int) - 1
    assert np.array_equal(_starts(id0), arr(fx["breakID_id"]).astype(int))


def test_group_moments_match_genXY(fx):
    inp = fx["inputs"]
    X, y = arr(inp["X"]), arr(inp["y"]).reshape(-1, 1)
    starts = _starts(arr(inp["id0"]).astype(int) - 1)
    assert np.allclose(_group_moments(X, y, starts), arr(fx["genXY"]), atol=TOL)
    assert np.allclose(_group_moments(X, X, starts), arr(fx["genXX"]), atol=TOL)


def test_beta_posterior_covariance_and_mean(fx):
    """sampleN's deterministic core, including the flat prior on coefficient 0."""
    inp = fx["inputs"]
    X, y, s2 = arr(inp["X"]), arr(inp["y"]), float(inp["sigma2"])
    k = X.shape[1]
    prec0 = np.zeros((k, k))
    for j in range(1, k):
        prec0[j, j] = 1.0 / 100.0
    S = np.linalg.inv(X.T @ X / s2 + prec0)
    mu = S @ (X.T @ y / s2)
    assert np.allclose(S, arr(fx["genCov1"]), atol=TOL)
    assert np.allclose(mu, arr(fx["genMu"]).ravel(), atol=TOL)


def test_tilde_expansion_with_and_without_a_block(fx):
    inp = fx["inputs"]
    X, F = arr(inp["X"]), arr(inp["F"])
    om = arr(inp["omega"])
    tcode = arr(inp["time"]).astype(int) - 1
    k, r = int(inp["k"]), int(inp["r"])
    assert np.allclose(_tilde(X, F, om, tcode), arr(fx["genTildeZ_full"]), atol=TOL)
    empty = np.zeros((X.shape[0], 0))
    assert np.allclose(_tilde(empty, F, om[k:k + r], tcode),
                       arr(fx["genTildeZ_bare"]), atol=TOL)


def test_tilde_tau_matches(fx):
    inp = fx["inputs"]
    X = arr(inp["X"])
    ucode = arr(inp["id0"]).astype(int) - 1
    tcode = arr(inp["time"]).astype(int) - 1
    got = _tilde_tau(X, X, arr(inp["Alpha"]), arr(inp["Xi"]),
                     arr(inp["Gamma"]), arr(inp["F"]), ucode, tcode)
    assert np.allclose(got, arr(fx["genTildeTau"]), atol=TOL)


def test_partial_fits_match(fx):
    inp = fx["inputs"]
    X = arr(inp["X"])
    ucode = arr(inp["id0"]).astype(int) - 1
    tcode = arr(inp["time"]).astype(int) - 1
    re_fit = np.einsum("ij,ij->i", X, arr(inp["Alpha"])[ucode])
    assert np.allclose(re_fit, arr(fx["getREfit"]), atol=TOL)
    ffit = np.einsum("ij,ij->i", arr(inp["Gamma"])[ucode], arr(inp["F"])[tcode])
    assert np.allclose(ffit, arr(fx["getFactorFit"]), atol=TOL)


def test_phi_posterior_moments_match(fx):
    """samplePhi's varphi and muphi (blasso.cpp:739-740)."""
    Xi = arr(fx["inputs"]["Xi"])
    lag = np.vstack([np.zeros((1, Xi.shape[1])), Xi[:-1]])
    xx, xy = lag.T @ lag, lag.T @ Xi
    assert np.allclose(xx, arr(fx["phi_xx"]), atol=TOL)
    assert np.allclose(xy, arr(fx["phi_xy"]), atol=TOL)
    k = Xi.shape[1]
    var = np.array([1.0 / (xx[i, i] + 1.0 / 100.0) for i in range(k)])
    mu = np.array([var[i] * xy[i, i] for i in range(k)])
    assert np.allclose(var, arr(fx["phi_var"]), atol=TOL)
    assert np.allclose(mu, arr(fx["phi_mu"]), atol=TOL)


FIX2 = pathlib.Path(__file__).parent / "fixtures" / "dmlfm" / "loading_and_state_steps.json"


@pytest.fixture(scope="module")
def fx2():
    if not FIX2.exists():  # pragma: no cover - fixture is committed
        pytest.skip("pblasso fixtures not generated")
    return json.loads(FIX2.read_text())


def test_loading_step_posterior_moments(fx2):
    """iterGenAlpha (blasso.cpp:367): per-unit A1 and bara."""
    from mlsynth.utils.dmlfm_helpers.sampler import _group_moments
    tZ, res = arr(fx2["tZ"]), arr(fx2["res"]).reshape(-1, 1)
    s2 = float(fx2["sigma2"])
    kk = tZ.shape[1]
    starts = _starts(arr(fx2["id0"]).astype(int) - 1)
    XX = _group_moments(tZ, tZ, starts)
    XY = _group_moments(tZ, res, starts)
    inv0 = np.linalg.inv(np.eye(kk))
    for i in range(int(fx2["N"])):
        A1 = np.linalg.inv(XX[i * kk:(i + 1) * kk] / s2 + inv0)
        mu = A1 @ XY[i * kk:(i + 1) * kk].ravel() / s2
        assert np.allclose(A1, arr(fx2["A1"][i]), atol=TOL), f"A1 unit {i}"
        assert np.allclose(mu, arr(fx2["bara"][i]).ravel(), atol=TOL), f"bara unit {i}"


def test_time_state_step_posterior_moments(fx2):
    """iterGenXi (blasso.cpp:619): per-period precision and mean, including the
    first period conditioning on its forward neighbour only."""
    from mlsynth.utils.dmlfm_helpers.sampler import _group_moments
    tA, res = arr(fx2["tA"]), arr(fx2["res"]).reshape(-1, 1)
    s2 = float(fx2["sigma2"])
    ucode = arr(fx2["id0"]).astype(int) - 1
    tcode = arr(fx2["time"]).astype(int) - 1
    order = np.lexsort((ucode, tcode))
    kk, TT = tA.shape[1], int(fx2["TT"])
    starts = _starts(tcode[order])
    XX = _group_moments(tA[order], tA[order], starts)
    XY = _group_moments(tA[order], res[order], starts)
    phi = arr(fx2["Phi"])
    tau_old = arr(fx2["TauOld"])
    I, mphi = np.eye(kk), np.diag(phi)
    pp = mphi @ mphi
    for t in range(TT):
        xx = XX[t * kk:(t + 1) * kk]
        xy = XY[t * kk:(t + 1) * kk].ravel()
        if t < TT - 1:
            prec = I + xx / s2 + pp
            mu = xy / s2 + (mphi @ tau_old[1] if t == 0
                            else mphi @ (tau_old[t - 1] + tau_old[t + 1]))
        else:
            prec = I + xx / s2
            mu = xy / s2 + mphi @ tau_old[t - 1]
        assert np.allclose(prec, arr(fx2["prec"][t]), atol=TOL), f"precision t={t}"
        assert np.allclose(np.linalg.inv(prec) @ mu, arr(fx2["mu"][t]).ravel(),
                           atol=TOL), f"mean t={t}"


FIX3 = pathlib.Path(__file__).parent / "fixtures" / "dmlfm" / "covariate_scaling.json"


@pytest.fixture(scope="module")
def fx3():
    if not FIX3.exists():  # pragma: no cover - fixture is committed
        pytest.skip("pblasso fixtures not generated")
    return json.loads(FIX3.read_text())


def test_covariate_scaling_matches_reference(fx3):
    """blasso_default.R:88-91 divides each covariate by its pooled standard
    deviation, denominator n-1, no centring.

    This was the root cause of the port's first mismatch on the German panel.
    Without it a covariate that is large in level -- ``pgdp`` runs to five
    figures here -- lets the time-varying coefficient block absorb the common
    structure the factor term should carry, which collapses the loading scales
    and leaves the counterfactual tracking the donors through the post-period.
    """
    import pandas as pd
    d = pd.read_stata("basedata/repgermany.dta", convert_categoricals=False)
    d = d.sort_values(["index", "year"])
    # the Stata columns are single precision; R reads them as double, so the
    # per-unit means must be accumulated in float64 to compare
    num = d.select_dtypes("number").columns
    d[num] = d[num].astype("float64")
    old = d.copy()
    for i in d["index"].unique():
        m = d["index"] == i
        s = old[old["index"] == i]
        d.loc[m, "pgdp"] = s.gdp.mean()
        d.loc[m, "trade"] = s.trade.mean()
        d.loc[m, "inflation"] = s.infrate.mean()
        d.loc[m, "industry"] = s.industry.mean()
        d.loc[m, "schooling"] = s.schooling.mean()
        d.loc[m, "invest"] = np.nanmean(
            s[["invest60", "invest70", "invest80"]].to_numpy())
    covs = fx3["covariates"]
    got = d[covs].to_numpy(float).std(axis=0, ddof=1)
    assert np.allclose(got, arr(fx3["scales"]), rtol=1e-9), (
        f"scales differ: {got} vs {arr(fx3['scales'])}")
