name: Build Documentation

on:
  push:
    branches:
      - main  # Adjust to your default branch name if it's not 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx_rtd_theme

    - name: Run the FDID analysis and save the plot
      run: |
        python -c "
import pandas as pd
import matplotlib.pyplot as plt
from mlsynth.mlsynth import FDID

# URL for the dataset
url = 'https://raw.githubusercontent.com/OscarEngelbrektson/SyntheticControlMethods/master/examples/datasets/basque_data.csv'

# Load the dataset directly from the URL
df = pd.read_csv(url)

# Configure the FDID model
config = {
    'df': df,
    'treat': 'Terrorism',
    'time': 'year',
    'outcome': 'gdpcap',
    'unitid': 'regionname',
    'counterfactual_color': '#7DF9FF',
    'treated_color': 'red',
    'display_graphs': False,  # Set to False to prevent displaying the graph
    'save': True  # Save the plot instead of displaying
}

model = FDID(config)
autores = model.fit()

# Save the plot if the "save" parameter is set to True
if config['save']:
    plt.savefig('docs/_static/fdid_analysis_plot.png')
    print('Plot saved to docs/_static/fdid_analysis_plot.png')
        "
    
    - name: Build the documentation
      run: |
        sphinx-build -b html docs/ docs/_build/html

    - name: Upload documentation to ReadTheDocs
      run: |
        pip install readthedocs
        readthedocs build --no-cache docs/
