name: Generate Plot for Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-plot:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have all dependencies listed in requirements.txt

    # Generate the plot and save it
    - name: Generate plot
      run: |
        import pandas as pd
        import matplotlib.pyplot as plt
        from mlsynth.mlsynth import FDID

        # URL for the dataset
        url = 'https://raw.githubusercontent.com/OscarEngelbrektson/SyntheticControlMethods/master/examples/datasets/basque_data.csv'

        # Load the dataset directly from the URL
        df = pd.read_csv(url)

        # Configure the FDID model
        config = {
            "df": df,
            "treat": "Terrorism",
            "time": "year",
            "outcome": "gdpcap",
            "unitid": "regionname",
            "counterfactual_color": "#7DF9FF",
            "treated_color": "red",
            "display_graphs": True
        }

        model = FDID(config)
        autores = model.fit()

        # Save the plot as an image
        plt.savefig('docs/_static/fdid_analysis_plot.png')
        
    # Commit the generated plot to the repository
    - name: Commit plot to repository
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/_static/fdid_analysis_plot.png
        git commit -m "Add generated plot for FDID analysis"
        git push
