name: Delete Old Workflow Runs

on:
  workflow_dispatch:  # Trigger manually

permissions:
  actions: write  # Grant write permissions for actions
  contents: read  # Grant read permissions for contents

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          # Install GitHub CLI
          sudo apt-get update
          sudo apt-get install gh
          gh --version  # Check if the installation was successful

      - name: List and delete oldest 500 runs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Use the new personal access token with workflow scope
        run: |
          # Get the database IDs of the oldest 500 runs
          gh run list --limit 500 --json databaseId -q '.[].databaseId' > runs_to_delete.txt
          
          # Loop through each ID and delete the corresponding run
          while read -r ID; do
            # Use the PAT (Personal Access Token) for the Authorization header
            if gh api "repos/${{ github.repository }}/actions/runs/${ID}" -X DELETE --header "Authorization: Bearer $GH_TOKEN"; then
              echo "Deleted run with ID: ${ID}"
            else
              echo "Failed to delete run with ID: ${ID}. Stopping the deletion process."
              break  # Stop the loop if deletion fails
            fi
          done < runs_to_delete.txt
