name: Run FDID, Basque

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_plot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .  # Install the mlsynth module from your local repository

    - name: Run FDID
      run: |
        python examples/fdidbasque.py

    - name: Find and commit the generated plot
      run: |
        # Find the most recently saved PNG file in the root directory
        plot_file=$(ls -t *.png | head -n 1)
        echo "Found plot file: $plot_file"
        
        # Commit and push the plot to the root directory
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Check if the plot file is already named fdid_analysis_plot.png, and only move if necessary
        if [ "$plot_file" != "fdid_analysis_plot.png" ]; then
          mv $plot_file fdid_analysis_plot.png
        else
          echo "Plot file is already named fdid_analysis_plot.png, overwriting it."
        fi

        # Clean up any unnecessary untracked files (like build/ and egg-info)
        git clean -fd
        
        # Stage the plot file explicitly (even if it's the same file, ensure it's added)
        git add fdid_analysis_plot.png

        # Check if there are any changes and commit them if necessary
        git diff --exit-code --quiet || git commit -m "Add generated FDID analysis plot"
        
        # Ensure the working directory is clean before pulling
        git reset --hard
        
        # Pull the latest changes from the remote to avoid non-fast-forward error
        git pull origin main --rebase
        
        # Push changes using personal access token (PAT) for authentication
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jgreathouse9/mlsynth.git HEAD:main
