name: Run FDID, Basque

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_plot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .  # Install the mlsynth module from your local repository

    - name: Run FDID
      run: |
        python examples/fdidbasque.py
        # Check if FDID_Basque.png was generated
        if [ -f "./FDID_Basque.png" ]; then
          echo "FDID_Basque.png generated in the root directory"
        else
          echo "FDID_Basque.png not found, checking other directories"
          find . -name "FDID_Basque.png"
        fi

    - name: Commit FDID_Basque.png
      run: |
        # Ensure that FDID_Basque.png exists in the root directory
        if [ -f "./FDID_Basque.png" ]; then
          echo "Staging FDID_Basque.png from the root directory"
          
          # Force add the FDID_Basque.png file even if it's ignored in .gitignore
          git add -f "./FDID_Basque.png"
        else
          echo "FDID_Basque.png not found, nothing to commit"
        fi
        
        # Commit the file only if it was staged
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Commit only if there are staged changes (not including build/ or egg-info)
        git diff --exit-code --quiet || git commit -m "Add FDID_Basque plot"
        
        # Check the status to ensure the file is committed
        git status

    - name: Pull changes from the remote repository before pushing
      run: |
        # Commit any staged changes before pulling
        git add .  # Make sure all changes are staged
        git commit -m "Committing staged changes before pull" || echo "No changes to commit"

        # Pull the latest changes from the remote repository
        git pull https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jgreathouse9/mlsynth.git main --rebase

    - name: Push the changes to the repository
      run: |
        # Push the changes to the remote repository
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jgreathouse9/mlsynth.git HEAD:main
