name: Run FDID, Basque

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_plot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .  # Install the mlsynth module from your local repository

    - name: Run FDID
      run: |
        python examples/fdidbasque.py
        # Check if FDID_Basque.png was generated in the example directory
        if [ -f "./examples/FDID_Basque.png" ]; then
          echo "FDID_Basque.png generated in examples/"
          
          # Create examples/fdid directory if it doesn't exist
          mkdir -p "./examples/fdid"
          
          # Move the plot to examples/fdid
          mv "./examples/FDID_Basque.png" "./examples/fdid/FDID_Basque.png"
        else
          echo "FDID_Basque.png not found in examples/"
          exit 1
        fi

    - name: Commit FDID_Basque.png
      run: |
        # Ensure that FDID_Basque.png exists in examples/fdid
        if [ -f "./examples/fdid/FDID_Basque.png" ]; then
          echo "Staging FDID_Basque.png from examples/fdid/"
          
          # Force add the file even if it's ignored by .gitignore
          git add -f "./examples/fdid/FDID_Basque.png"
        else
          echo "FDID_Basque.png not found, nothing to commit"
        fi
        
        # Configure Git for committing
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Commit only if there are staged changes
        git diff --exit-code --quiet || git commit -m "Add FDID_Basque plot"

    - name: Pull changes from the remote repository before pushing
      run: |
        # Commit any staged changes before pulling
        git add .  # Make sure all changes are staged
        git commit -m "Committing staged changes before pull" || echo "No changes to commit"

        # Pull the latest changes from the remote repository
        git pull https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jgreathouse9/mlsynth.git main --rebase

    - name: Push the changes to the repository
      run: |
        # Push the changes to the remote repository
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jgreathouse9/mlsynth.git HEAD:main
