name: Run FDID, Basque

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_plot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .  # Install the mlsynth module from your local repository

    - name: Run FDID
      run: |
        python examples/fdidbasque.py

    - name: Find and commit the generated plot
      run: |
        # Find the most recently saved PNG file in the root directory
        plot_file=$(ls -t *.png | head -n 1)
        echo "Found plot file: $plot_file"
        
        # Commit and push the plot to the root directory
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Move the file to the root if it's not already there
        mv $plot_file ./fdid_analysis_plot.png

        # Stage and commit the plot image
        git add fdid_analysis_plot.png
        git commit -m "Add generated FDID analysis plot"
        
        # Pull the latest changes from the remote to avoid non-fast-forward error
        git pull origin main --rebase
        
        # Push changes using personal access token (PAT) for authentication
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jgreathouse9/mlsynth.git HEAD:main
