name: Unzip File

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "ZIP file to unzip"
        required: true
        type: string

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unzip file
        run: |
          unzip "${{ github.event.inputs.filename }}" -d extracted
